#version: "3.0" # deprecated

services:
  mariadb:
    image: my-mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - ${VOLUME_PATH}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ./.env
  wordpress:
    image: my-wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - 9000:9000
    volumes:
      - ${VOLUME_PATH}/wordpress:/var/www/html

  #marimari:
  #  image: my-mariadb
  #  depends_on:
  #    - mariadb
  #  networks:
  #    - inception
  #  env_file:
  #    - ./.env
  #  command: /bin/sh

networks:
  inception:
    driver: bridge
volumes:
  wpdata:
