#version: "3.0" # deprecated

services:
  mariadb:
    image: my-mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - inception
    volumes:
    # TODO : volume change to bind mount
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ./.env
  #wordpress:
  #  image: my-wordpress
  #  build:
  #    context: ./requirements/wordpress
  #  depends-on:
  #    - mariadb
  #  networks:
  #    - inception
  #  volumes:
  #    - wpdata:/var/www/html

networks:
  inception:
    driver: bridge
volumes:
  wpdata:
  wp_mariadb:
