version: "3.9" # deprecated

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${WP_DATABASE}
    networks:
      - inception
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"
    init: true
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_DB_NAME: ${WP_DATABASE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
    networks:
      - inception
    volumes:
      - wpdata:/wordpress
    expose:
      - "9000"
    init: true
    restart: on-failure
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - inception
    volumes:
      - wpdata:/var/www/html
    ports:
      - "443:443"
    init: true
    restart: on-failure
networks:
  inception:
    name: inception
    driver: bridge
volumes:
  dbdata:
    name: dbdata
    driver: local # default
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/mariadb # 볼륨 저장 위치
      o: bind # `mount` 커맨드에 전달됨.
  wpdata:
    name: wpdata
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/wordpress
      o: bind
